// Stamps the build with a version so the app can detect when a newer deploy is
// live and refresh past the browser cache. Runs before dev/build.
import { writeFileSync, mkdirSync } from "node:fs";

const version = (process.env.GITHUB_SHA || "").slice(0, 7) || String(Date.now());

// Baked into the JS bundle (the version this build is).
writeFileSync(
  "lib/version.ts",
  `// Auto-generated by scripts/stamp-version.mjs — do not edit.\nexport const BUILD_VERSION = ${JSON.stringify(version)};\n`,
);

// Served as a static file (the version currently on the server).
mkdirSync("public", { recursive: true });
writeFileSync("public/version.json", JSON.stringify({ version }));

console.log("Stamped build version:", version);
