/**
 * Synthetic practice statements (written for this tool). keyed = +1 when
 * agreeing expresses more of the subscale, -1 when it expresses less.
 */
export interface BankStatement {
  id: string;
  text: string;
  en: string;
  subscale: string;
  keyed: 1 | -1;
}

const S = (id: string, subscale: string, keyed: 1 | -1, text: string, en: string): BankStatement => ({ id, subscale, keyed, text, en });

export const STATEMENT_BANK: BankStatement[] = [
  S("soc1", "sociability", 1, "Jag trivs bäst när jag är omgiven av många människor.", "I feel best when surrounded by many people."),
  S("soc2", "sociability", -1, "Jag föredrar att arbeta ensam framför att arbeta i grupp.", "I prefer working alone to working in a group."),
  S("soc3", "sociability", 1, "Jag tar gärna kontakt med nya människor på jobbet.", "I readily approach new people at work."),
  S("ass1", "assertiveness", 1, "Jag tar gärna ledningen när en grupp behöver en riktning.", "I readily take the lead when a group needs direction."),
  S("ass2", "assertiveness", -1, "Jag låter hellre andra bestämma i möten.", "I would rather let others decide in meetings."),
  S("ass3", "assertiveness", 1, "Jag säger ifrån när jag inte håller med.", "I speak up when I disagree."),
  S("act1", "activity", 1, "Jag gillar att ha många saker på gång samtidigt.", "I like having many things going on at once."),
  S("act2", "activity", -1, "Jag trivs bäst i ett lugnt och jämnt arbetstempo.", "I thrive in a calm, steady pace of work."),
  S("act3", "activity", 1, "Jag blir rastlös om det händer för lite.", "I get restless when too little is happening."),
  S("exc1", "excitement", 1, "Jag söker mig till utmaningar som innebär en viss risk.", "I seek out challenges that involve some risk."),
  S("exc2", "excitement", -1, "Jag föredrar det förutsägbara framför det spännande.", "I prefer the predictable to the exciting."),
  S("exc3", "excitement", 1, "Jag tycker om att göra saker jag aldrig gjort förut.", "I enjoy doing things I have never done before."),
  S("che1", "cheerfulness", 1, "Jag visar ofta min entusiasm för andra.", "I often show my enthusiasm to others."),
  S("che2", "cheerfulness", -1, "Jag är sällan uppspelt eller entusiastisk.", "I am rarely excited or enthusiastic."),
  S("che3", "cheerfulness", 1, "Jag skrattar lätt och ofta.", "I laugh easily and often."),
  S("tru1", "trust", 1, "Jag utgår från att de flesta människor har goda avsikter.", "I assume most people have good intentions."),
  S("tru2", "trust", -1, "Jag är ofta misstänksam mot andras motiv.", "I am often suspicious of other people's motives."),
  S("tru3", "trust", 1, "Jag litar på mina kollegor tills jag har skäl att inte göra det.", "I trust my colleagues until I have reason not to."),
  S("coo1", "cooperation", 1, "Jag försöker hitta kompromisser när åsikter går isär.", "I try to find compromises when opinions differ."),
  S("coo2", "cooperation", -1, "Jag har inga problem med att hamna i konflikt för att få min vilja igenom.", "I don't mind getting into conflict to get my way."),
  S("coo3", "cooperation", 1, "Jag sätter gruppens enighet före att vinna en diskussion.", "I put group agreement before winning an argument."),
  S("alt1", "altruism", 1, "Jag ställer gärna upp när en kollega behöver hjälp.", "I gladly step in when a colleague needs help."),
  S("alt2", "altruism", -1, "Jag prioriterar mina egna uppgifter före att hjälpa andra.", "I prioritise my own tasks over helping others."),
  S("alt3", "altruism", 1, "Jag hjälper andra även när det tar tid från mitt eget arbete.", "I help others even when it takes time from my own work."),
  S("mod1", "modesty", 1, "Jag pratar sällan om mina egna prestationer.", "I rarely talk about my own achievements."),
  S("mod2", "modesty", -1, "Jag tycker om att få uppmärksamhet för det jag åstadkommer.", "I like getting attention for what I accomplish."),
  S("mod3", "modesty", 1, "Jag ser mig inte som bättre än andra.", "I don't see myself as better than others."),
  S("emp1", "empathy", 1, "Jag märker snabbt när någon i min närhet mår dåligt.", "I quickly notice when someone near me is unhappy."),
  S("emp2", "empathy", -1, "Jag fokuserar mer på fakta än på hur andra känner sig.", "I focus more on facts than on how others feel."),
  S("emp3", "empathy", 1, "Andras känslor påverkar mig.", "Other people's feelings affect me."),
  S("ord1", "order", 1, "Jag håller ordning på mina saker och dokument.", "I keep my things and documents in order."),
  S("ord2", "order", -1, "Det stör mig inte om det är rörigt på skrivbordet.", "It doesn't bother me if my desk is messy."),
  S("ord3", "order", 1, "Jag arbetar helst efter ett tydligt system.", "I prefer working according to a clear system."),
  S("dut1", "dutifulness", 1, "Jag håller alltid det jag lovar.", "I always keep my promises."),
  S("dut2", "dutifulness", -1, "Jag tycker att regler ibland är till för att tänjas.", "I think rules are sometimes meant to be bent."),
  S("dut3", "dutifulness", 1, "Jag lämnar in mitt arbete i tid.", "I hand in my work on time."),
  S("ach1", "achievement", 1, "Jag sätter högt ställda mål för mig själv.", "I set high goals for myself."),
  S("ach2", "achievement", -1, "Jag nöjer mig ofta med att något är tillräckligt bra.", "I am often content when something is good enough."),
  S("ach3", "achievement", 1, "Jag vill vara bäst på det jag gör.", "I want to be the best at what I do."),
  S("dis1", "discipline", 1, "Jag slutför mina uppgifter även när de är tråkiga.", "I finish my tasks even when they are boring."),
  S("dis2", "discipline", -1, "Jag skjuter ofta upp saker till sista minuten.", "I often put things off until the last minute."),
  S("dis3", "discipline", 1, "Jag behåller fokus på en uppgift tills den är klar.", "I stay focused on a task until it is done."),
  S("del1", "deliberation", 1, "Jag planerar alltid mitt arbete noggrant.", "I always plan my work carefully."),
  S("del2", "deliberation", -1, "Jag fattar ofta beslut spontant.", "I often make decisions spontaneously."),
  S("del3", "deliberation", 1, "Jag tänker igenom konsekvenserna innan jag agerar.", "I think through the consequences before I act."),
  S("cal1", "calm", -1, "Jag oroar mig ofta för saker som kan gå fel.", "I often worry about things that could go wrong."),
  S("cal2", "calm", 1, "Jag är för det mesta lugn och avslappnad.", "I am mostly calm and relaxed."),
  S("cal3", "calm", -1, "Jag känner mig ofta nervös inför nya situationer.", "I often feel nervous before new situations."),
  S("str1", "stress", 1, "Jag presterar bra även under stark tidspress.", "I perform well even under strong time pressure."),
  S("str2", "stress", -1, "Jag blir lätt stressad när mycket händer samtidigt.", "I easily get stressed when a lot happens at once."),
  S("str3", "stress", 1, "Jag behåller överblicken när det blir kaotiskt.", "I keep the overview when things get chaotic."),
  S("con1", "confidence", 1, "Jag känner mig säker på min egen förmåga.", "I feel confident in my own abilities."),
  S("con2", "confidence", -1, "Jag tvivlar ofta på om jag klarar mina uppgifter.", "I often doubt whether I can handle my tasks."),
  S("con3", "confidence", 1, "Jag tror på mina egna bedömningar.", "I trust my own judgements."),
  S("ctl1", "control", -1, "Jag blir lätt irriterad när saker inte går som planerat.", "I get irritated easily when things don't go as planned."),
  S("ctl2", "control", 1, "Jag behåller lugnet även när någon provocerar mig.", "I stay calm even when someone provokes me."),
  S("ctl3", "control", -1, "Mina känslor syns tydligt när jag är frustrerad.", "My feelings show clearly when I am frustrated."),
  S("res1", "resilience", 1, "Jag kommer snabbt igen efter ett misslyckande.", "I bounce back quickly after a failure."),
  S("res2", "resilience", -1, "Kritik kan påverka mitt humör länge.", "Criticism can affect my mood for a long time."),
  S("res3", "resilience", 1, "Motgångar får mig att anstränga mig mer.", "Setbacks make me try harder."),
  S("ima1", "imagination", 1, "Jag får ofta nya idéer.", "I often come up with new ideas."),
  S("ima2", "imagination", -1, "Jag föredrar praktiska lösningar framför kreativa experiment.", "I prefer practical solutions to creative experiments."),
  S("ima3", "imagination", 1, "Jag tycker om att fantisera om hur saker skulle kunna vara.", "I enjoy imagining how things could be."),
  S("cur1", "curiosity", 1, "Jag tycker om att lära mig nya saker.", "I enjoy learning new things."),
  S("cur2", "curiosity", -1, "Jag är mer intresserad av det som är användbart nu än av nya teorier.", "I care more about what is useful now than about new theories."),
  S("cur3", "curiosity", 1, "Jag är nyfiken på hur saker fungerar.", "I am curious about how things work."),
  S("chg1", "change", 1, "Jag välkomnar förändringar på arbetsplatsen.", "I welcome changes in the workplace."),
  S("chg2", "change", -1, "Jag föredrar beprövade rutiner framför nya arbetssätt.", "I prefer proven routines to new ways of working."),
  S("chg3", "change", 1, "Jag tycker om variation i mina arbetsuppgifter.", "I like variety in my tasks."),
  S("aes1", "aesthetics", 1, "Jag lägger märke till design och form i min omgivning.", "I notice design and form around me."),
  S("aes2", "aesthetics", -1, "Konst och musik betyder inte särskilt mycket för mig.", "Art and music don't mean much to me."),
  S("aes3", "aesthetics", 1, "Jag kan bli berörd av vacker musik.", "I can be moved by beautiful music."),
  S("ana1", "analysis", 1, "Jag tycker om att lösa komplexa problem.", "I enjoy solving complex problems."),
  S("ana2", "analysis", -1, "Jag föredrar enkla och konkreta uppgifter.", "I prefer simple, concrete tasks."),
  S("ana3", "analysis", 1, "Jag gillar att analysera saker på djupet.", "I like analysing things in depth."),
];
